# Generated by Django 3.2.23 on 2024-01-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20240115_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_tag',
            field=models.CharField(blank=True, choices=[{'label': 'Tribal', 'value': 'tribal'}, {'label': 'Geometric', 'value': 'geometric'}, {'label': 'Realism', 'value': 'realism'}, {'label': 'Portraits', 'value': 'portraits'}, {'label': 'Illustrative', 'value': 'illustrative'}, {'label': 'Dotwork', 'value': 'dotwork'}, {'label': 'Watercolour', 'value': 'watercolour'}, {'label': 'Neo-traditional', 'value': 'neo-traditional'}, {'label': 'Abstract', 'value': 'abstract'}, {'label': 'Animals', 'value': 'animals'}, {'label': 'Lettering', 'value': 'lettering'}, {'label': 'Traditional', 'value': 'traditional'}], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_tag2',
            field=models.CharField(blank=True, choices=[{'label': 'Tribal', 'value': 'tribal'}, {'label': 'Geometric', 'value': 'geometric'}, {'label': 'Realism', 'value': 'realism'}, {'label': 'Portraits', 'value': 'portraits'}, {'label': 'Illustrative', 'value': 'illustrative'}, {'label': 'Dotwork', 'value': 'dotwork'}, {'label': 'Watercolour', 'value': 'watercolour'}, {'label': 'Neo-traditional', 'value': 'neo-traditional'}, {'label': 'Abstract', 'value': 'abstract'}, {'label': 'Animals', 'value': 'animals'}, {'label': 'Lettering', 'value': 'lettering'}, {'label': 'Traditional', 'value': 'traditional'}], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_tag3',
            field=models.CharField(blank=True, choices=[{'label': 'Tribal', 'value': 'tribal'}, {'label': 'Geometric', 'value': 'geometric'}, {'label': 'Realism', 'value': 'realism'}, {'label': 'Portraits', 'value': 'portraits'}, {'label': 'Illustrative', 'value': 'illustrative'}, {'label': 'Dotwork', 'value': 'dotwork'}, {'label': 'Watercolour', 'value': 'watercolour'}, {'label': 'Neo-traditional', 'value': 'neo-traditional'}, {'label': 'Abstract', 'value': 'abstract'}, {'label': 'Animals', 'value': 'animals'}, {'label': 'Lettering', 'value': 'lettering'}, {'label': 'Traditional', 'value': 'traditional'}], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_tag4',
            field=models.CharField(blank=True, choices=[{'label': 'Tribal', 'value': 'tribal'}, {'label': 'Geometric', 'value': 'geometric'}, {'label': 'Realism', 'value': 'realism'}, {'label': 'Portraits', 'value': 'portraits'}, {'label': 'Illustrative', 'value': 'illustrative'}, {'label': 'Dotwork', 'value': 'dotwork'}, {'label': 'Watercolour', 'value': 'watercolour'}, {'label': 'Neo-traditional', 'value': 'neo-traditional'}, {'label': 'Abstract', 'value': 'abstract'}, {'label': 'Animals', 'value': 'animals'}, {'label': 'Lettering', 'value': 'lettering'}, {'label': 'Traditional', 'value': 'traditional'}], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_tag5',
            field=models.CharField(blank=True, choices=[{'label': 'Tribal', 'value': 'tribal'}, {'label': 'Geometric', 'value': 'geometric'}, {'label': 'Realism', 'value': 'realism'}, {'label': 'Portraits', 'value': 'portraits'}, {'label': 'Illustrative', 'value': 'illustrative'}, {'label': 'Dotwork', 'value': 'dotwork'}, {'label': 'Watercolour', 'value': 'watercolour'}, {'label': 'Neo-traditional', 'value': 'neo-traditional'}, {'label': 'Abstract', 'value': 'abstract'}, {'label': 'Animals', 'value': 'animals'}, {'label': 'Lettering', 'value': 'lettering'}, {'label': 'Traditional', 'value': 'traditional'}], max_length=50),
        ),
    ]
