# Generated by Django 3.2.23 on 2024-01-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20240117_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_tag',
            field=models.CharField(blank=True, choices=[('tribal', 'Tribal'), ('geometric', 'Geometric'), ('realism', 'Realism'), ('portraits', 'Portraits'), ('illustrative', 'Illustrative'), ('dotwork', 'Dotwork'), ('watercolour', 'Watercolour'), ('neo-traditional', 'Neo-traditional'), ('abstract', 'Abstract'), ('animals', 'Animals'), ('lettering', 'Lettering'), ('traditional', 'Traditional')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_tag2',
            field=models.CharField(blank=True, choices=[('tribal', 'Tribal'), ('geometric', 'Geometric'), ('realism', 'Realism'), ('portraits', 'Portraits'), ('illustrative', 'Illustrative'), ('dotwork', 'Dotwork'), ('watercolour', 'Watercolour'), ('neo-traditional', 'Neo-traditional'), ('abstract', 'Abstract'), ('animals', 'Animals'), ('lettering', 'Lettering'), ('traditional', 'Traditional')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_tag3',
            field=models.CharField(blank=True, choices=[('tribal', 'Tribal'), ('geometric', 'Geometric'), ('realism', 'Realism'), ('portraits', 'Portraits'), ('illustrative', 'Illustrative'), ('dotwork', 'Dotwork'), ('watercolour', 'Watercolour'), ('neo-traditional', 'Neo-traditional'), ('abstract', 'Abstract'), ('animals', 'Animals'), ('lettering', 'Lettering'), ('traditional', 'Traditional')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_tag4',
            field=models.CharField(blank=True, choices=[('tribal', 'Tribal'), ('geometric', 'Geometric'), ('realism', 'Realism'), ('portraits', 'Portraits'), ('illustrative', 'Illustrative'), ('dotwork', 'Dotwork'), ('watercolour', 'Watercolour'), ('neo-traditional', 'Neo-traditional'), ('abstract', 'Abstract'), ('animals', 'Animals'), ('lettering', 'Lettering'), ('traditional', 'Traditional')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_tag5',
            field=models.CharField(blank=True, choices=[('tribal', 'Tribal'), ('geometric', 'Geometric'), ('realism', 'Realism'), ('portraits', 'Portraits'), ('illustrative', 'Illustrative'), ('dotwork', 'Dotwork'), ('watercolour', 'Watercolour'), ('neo-traditional', 'Neo-traditional'), ('abstract', 'Abstract'), ('animals', 'Animals'), ('lettering', 'Lettering'), ('traditional', 'Traditional')], max_length=50),
        ),
    ]
