# Generated by Django 3.2.23 on 2024-01-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='content',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('ink slinger', 'Ink Slinger'), ('ink addict', 'Ink Addict'), ('both', 'Both'), ('neither', 'Neither')], max_length=50),
        ),
    ]
