# Generated by Django 3.2.23 on 2024-01-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20240115_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('ink slinger', 'Ink Slinger'), ('ink addict', 'Ink Addict'), ('loooking for inspo', 'Looking for Inspo')], max_length=50),
        ),
    ]
