# Generated by Django 3.2.23 on 2024-01-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('Ink Slinger', 'Ink Slinger'), ('Ink Addict', 'Ink Addict'), ('Looking for Inspo', 'Looking for Inspo')], max_length=50),
        ),
    ]
